# url: https://www.semi.technology
weaviate_version: 0.22.14
slack_signup_url: "https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw"
helm_version: 10.0.0
markdown: kramdown
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
collections:
    news:
        output: true
        permalink: /news/:path
    jobs:
        output: true
        permalink: /jobs/:path
    use_cases:
        output: true
        permalink: /use-cases/:path
    documentation:
        output: true
        permalink: /documentation/:path
    marketplace:
        output: true
        permalink: /marketplace/:path
    playbook:
        output: true
        permalink: /playbook/:path
    authors:
        output: true
    solutions:
        output: true
        permalink: /solutions/:path
    thank-you:
        output: true
        permalink: /thank-you/:path
    newsletter:
        output: true
        permalink: /newsletter/:path
    about:
        output: true
        permalink: /about/:path
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
    - node_modules
    - webpack.config.js
plugins:
    - jekyll-redirect-from
    - jekyll-toc
whitelist:
    - jekyll-redirect-from
docs:
    weaviate:
        - Get started
        - Setup
        - Add data
        - Query data
        - Classification
        - Transfer learning
        - Additional features
        - Datasets
        - Client libs
        - Weaviate Cluster Service
        - More resources
        - About
    contributor-guide:
        - Build, Run, Test
        - Custom DB
        - Contextionary
