<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
weaviate_version: 0.22.9
helm_version: 10.0.0
=======
weaviate_version: 0.21.6
helm_version: 8.2.0
>>>>>>> gh-416: General updates to the docs
=======
weaviate_version: 0.21.12
=======
weaviate_version: 0.22.0
>>>>>>> gh-423: general updates
helm_version: 8.2.1
>>>>>>> gh-423: product page updates
=======
weaviate_version: 0.22.7
helm_version: 9.1.0
>>>>>>> gh-000: update to latest version
markdown: kramdown
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
collections:
    news:
        output: true
        permalink: /news/:path
    use_cases:
        output: true
        permalink: /use-cases/:path
    documentation:
        output: true
        permalink: /documentation/:path
    marketplace:
        output: true
        permalink: /marketplace/:path
    authors:
        output: true
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
    - node_modules
    - webpack.config.js
plugins:
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
docs:
    weaviate:
        - Get started
        - Setup
        - Add data
        - Query data
<<<<<<< HEAD
        - Classification
        - Transfer learning
        - Additional Features
=======
        - Features
>>>>>>> gh-416: General updates to the docs
        - Datasets
        - Client libs
        - Weaviate Cluster Service
        - More resources
        - About
    weaviate-cli:
        - Get started
        - Cluster
        - Schema
        - Misc